name: CI

on:
  push:
    branches:
      - main   # Only trigger when code is merged to main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    env:
      DATABRICKS_HOST: ${{ secrets.DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEPLOYMENT_TARGET_TOKEN }}
      REPO_PATH: /Workspace/Users/arul1020253@gmail.com/git-cicd/assetbundle-databricks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy to Dev (main branch)
        run: |
          echo "Deploying DEV environment on branch main"
          databricks repos update ${{ env.REPO_PATH }} --branch "main"
          databricks bundle deploy --target dev

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev    # deployment started only dev got succeded
    environment: production
    env:
      DATABRICKS_HOST: ${{ secrets.DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEPLOYMENT_TARGET_TOKEN }}
      REPO_PATH: /Workspace/Users/arul1020253@gmail.com/git-cicd/assetbundle-databricks-prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy to Prod (after Dev)
        run: |
          echo "Deploying PROD environment on branch main"
          databricks repos update ${{ env.REPO_PATH }} --branch "main"
          databricks bundle deploy --target prod
